### PR TITLE
Additional features to Kuttl

### PR DESCRIPTION
**Pull request by kanishkarj**
**What this PR does / why we need it**:

Here are the changes that I have made, Please review them and let me know. I have added some details regarding the same in the README.

Fixes #

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@kanishkarj we have a couple conflicts to resolve here.

**Comment by leecalcote** [comment]
Good to merge after conflicts are tidied up. 👍

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@kanishkarj, heads-up there are a couple conflicts to resolve.

**Comment by kushthedude** [comment]
https://github.com/layer5io/kuttl/pull/2#issuecomment-663056223

**Pull request closed without merging**
